apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "ws-flare-gateway.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: {{ template "ws-flare-gateway.fullname" . }}
              servicePort: 80
