# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "storage-mysql.fullname" . }}
  labels:
    app: {{ template "storage-mysql.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: {{ template "storage-mysql.fullname" . }}
    port: 3306
  clusterIP: None
  selector:
    app: {{ template "storage-mysql.fullname" . }}
---
# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the master: mysql-0.mysql.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "storage-mysql.fullname" . }}-readonly
  labels:
    app: {{ template "storage-mysql.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
  - name: {{ template "storage-mysql.fullname" . }}
    port: 3306
  selector:
    app: {{ template "storage-mysql.fullname" . }}