environment: dev

wsFlareGatewayImage: wsflare/ws-flare-gateway:1
wsFlareUiImage: wsflare/ws-flare-ui:1
wsFlareUserApiImage: wsflare/ws-flare-user-api:2

### Messaging
messagingRabbitmqImage: bitnami/rabbitmq:3.7.7-debian-9

serviceType: ClusterIP
ImagePullPolicy: Always