apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "messaging-rabbitmq.fullname" . }}-config
  labels:
    app: {{ template "messaging-rabbitmq.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  enabled_plugins: |-
{{ .Values.rabbitmq.plugins | indent 4 }}
  rabbitmq.conf: |-
    ##username and password
    default_user={{.Values.rabbitmq.username}}
    default_pass=CHANGEME
{{ .Values.rabbitmq.configuration | indent 4 }}
