kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "messaging-rabbitmq.fullname" . }}-endpoint-reader
  labels:
    app: {{ template "messaging-rabbitmq.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get"]