apiVersion: v1
kind: Secret
metadata:
  name: {{ template "messaging-rabbitmq.fullname" . }}
  labels:
    app: {{ template "messaging-rabbitmq.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  rabbitmq-password: {{ .Values.rabbitmq.password | b64enc | quote }}
  rabbitmq-erlang-cookie: {{ randAlphaNum 32 | b64enc | quote }}