apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "messaging-rabbitmq.fullname" . }}
  labels:
    app: {{ template "messaging-rabbitmq.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"