apiVersion: v1
kind: Service
metadata:
  name: {{ template "messaging-rabbitmq.fullname" . }}
  labels:
    app: {{ template "messaging-rabbitmq.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
    - name: epmd
      port: 4369
      targetPort: epmd
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: dist
      port: 25672
      targetPort: dist
    - name: stats
      port: 15672
      targetPort: stats
  selector:
    app: {{ template "messaging-rabbitmq.fullname" . }}
    release: "{{ .Release.Name }}"